
# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'app'

# The runtime the application uses.
type: 'python:3.8'

# The build-time dependencies of the app.
dependencies:
    python3:
       pipenv: '2018.10.13'
       jupyter-book: '0.7.4'

# The hooks executed at various points in the lifecycle of the application.
hooks:
  # The build hook runs before the application is deployed, and is useful for
  # assembling the codebase.
  build: |
    pipenv install
    pipenv run jupyter-book build platformsh

web:
    commands:
      # Run a no-op process that uses no CPU resources, since this is a static site.
      start: sleep infinity
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'platform/_build/html'
            passthru: true
            index: ['index.html']
            scripts: false
            allow: true
            expires: 24h
            rules:
                \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|cast|mp4|json|yaml|ico|svg?|cast|mp4|json|yaml|svg?|ttf)$:
                    expires: 4w


# # The size of the persistent disk of the application (in MB).
# disk: 512

# # Set a local R/W mount for logs
# mounts:
#     'logs':
#         source: local
#         source_path: logs
