# Book settings
title: Jupyter Book on Platform.sh
author: Platform.sh
logo: logo.png
exclude_patterns: 
  - ".global/*"
  - "test/.ipynb_checkpoints/*"

latex:
  latex_documents:
    targetname: book.tex
